- name: RAADS-R Test
  url: https://raadsrtest.com
  description: Free autism spectrum self-assessment tool based on the scientifically validated RAADS-R questionnaire. Helps adults screen for autism traits.
  tagline: Free Autism Spectrum Self-Assessment
  category: Mental Health
  features:
    - Scientifically validated
    - Completely free
    - Instant results
    - Privacy focused

- name: MindSpectrum
  url: https://mindspectrum.org
  description: Professional autism assessment platform offering multiple scientific scales including RAADS-R, AQ, and CAT-Q. Comprehensive neurodiversity insights.
  tagline: Professional Autism Assessment Platform
  category: Mental Health
  features:
    - Multiple assessment scales
    - Detailed analysis
    - Science-backed methods
    - User-friendly interface

- name: FunAudioChat
  url: https://funaudiochat.org
  description: End-to-end speech-to-speech AI experience powered by Alibaba's open-source FunAudioLLM. Seamless voice recognition, understanding, and synthesis.
  tagline: End-to-End Speech AI
  category: AI Tools
  features:
    - End-to-end voice interaction
    - Alibaba open-source tech
    - Natural conversations
    - High-quality synthesis
